
name: CI

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3

       - uses: actions/setup-node@v3
         with:
           node-version: '16'

       - name: Install Dependencies
         run: npm install

       - name: Build Vite Application
         run: npm build

       - name: Depoly SCP
         uses: appleboy/scp-action@master
         with:
          host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
          username: ${{ secrets.SERVER_NAME }} # 원격 서버 사용자 이름
          key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
          port: 22
          source: "./dist, ./server"
          target: "/home/sungsin/vue_source"
          
          
       - name: Run createJar.sh on Remote Server
         uses: appleboy/ssh-action@master
         with:
          host: ${{ secrets.SERVER_HOST }} # 원격 서버 IP 주소
          username: ${{ secrets.SERVER_NAME }} # 원격 서버 사용자 이름
          key: ${{ secrets.SERVER_KEY }} # 서버의 SSH 개인 키
          port: 22
          script: |
           npm run build
